### ISSUE TITLE
[UT] PresenceServiceImpl

### ISSUE THREAD

**Issue by dlazzaro** [qb-team/Stalker-Backend#136]
test classe PresenceServiceImpl:

- [ ] TUB102 & Si verifichi che venga restituito un Optional di OrganizationPresenceCounter dato un organizationId.
- [ ] TUB103 & Si verifichi che venga restituito un Optional di OrganizationPresenceCounter dato un organizationId.

**Comment by dlazzaro** [comment]
TUTTI NULL POINTER EXCEPTION

**Comment by TommasoAzz** [comment]
> TUTTI NULL POINTER EXCEPTION

Fai lo scaricabarile @dlazzaro ?

**Comment by dlazzaro** [comment]
> > TUTTI NULL POINTER EXCEPTION
> 
> Fai lo scaricabarile @dlazzaro ?

mi sa che il redis template non si può mockare, è l'unica spiegazione che mi riesco a dare

**Comment by TommasoAzz** [comment]
> 
> 
> > > TUTTI NULL POINTER EXCEPTION
> > 
> > 
> > Fai lo scaricabarile @dlazzaro ?
> 
> mi sa che il redis template non si può mockare, è l'unica spiegazione che mi riesco a dare

Darò un occhio
